---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: arun2sr/cloudservice:v1
        ports:
        - containerPort: 80   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: cloudservice-service
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 80
  type: LoadBalancer
